SG-34295 - Rebranding
shotgunsoftware/tk-flame pull request #136
Opened 2024-01-24 21:53 UTC by juanburgosautoglb

Change all the shotgrid/shotgun occurrences in the repository.

2024-03-02 00:39 UTC, julien-lang requested changes
A couple of issues here.

Also, what about the following code in flame_hooks/sg_hook.py: 
```python
    name = (
        "Shotgun"
        if version_major < 2022 or version_major == 2022 and version_minor <= 0
        else "ShotGrid"
    )
```

Should that be updated too @jpbrault?

2024-03-02 00:39 UTC, julien-lang commented on flame_assist_icon_256.png
Problem here!!

2024-03-02 00:39 UTC, julien-lang commented on icon_256.png
Problem here!

2024-03-11 13:09 UTC, jpbrault commented
> A couple of issues here.
> 
> Also, what about the following code in flame_hooks/sg_hook.py:
> 
> ```python
>     name = (
>         "Shotgun"
>         if version_major < 2022 or version_major == 2022 and version_minor <= 0
>         else "ShotGrid"
>     )
> ```
> 
> Should that be updated too @jpbrault?

This need to match what is in the Flame code base.
I assume there will be a matching PR in the Flame code base, however it need to match already realeased version as well.

2024-03-11 13:09 UTC, jpbrault approved these changes

2024-03-12 16:15 UTC, julien-lang approved these changes
LGTM!

2024-03-20 21:14 UTC, merged